---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/compliance"
    schedule:
      interval: "daily"
    labels:
      - automation
    open-pull-requests-limit: 10
