---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/code/go"
    schedule:
      interval: "daily"
    labels:
      - automation
    reviewers:
      - "mtojek"
      - "jsoriano"
    open-pull-requests-limit: 10
