queue_rules:
  - name: default
    conditions:
      - check-success=buildkite/package-spec
      - check-success=CLA

pull_request_rules:
  - name: automatic merge of bot 🤖
    conditions:
      - check-success=buildkite/package-spec
      - check-success=CLA
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: squash
        name: default
