env:
  SETUP_GVM_VERSION: 'v0.5.1' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  GOLANG_VERSION: "1.20.3"
  GH_CLI_VERSION: "2.29.0"
  JQ_VERSION: "1.6"

steps:
  - label: ":go: Run check-static"
    key: check
    command: "make check"
    agents:
      image: "golang:${GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"
  - label: ":linux: Tests on Linux"
    key: test
    command: "make test-ci"
    agents:
      image: "golang:${GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"

  - label: ":hammer: Create PR in integrations"
    key: pr-integrations
    command: ".buildkite/scripts/test-with-integrations.sh"
    agents:
      provider: "gcp"
    depends_on:
      - check
      - test


