# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: 'v0.5.1' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  SETUP_MAGE_VERSION: "latest"
  DOCKER_COMPOSE_VERSION: "v2.17.2"
  GO_LINUX_AGENT_IMAGE: "golang:${GO_VERSION}"
  GO_WINDOWS_AGENT_IMAGE: "family/core-windows-2022"

  # Allow the use of go.mod toolchains, given that we have multiple go.mods in the repository.
  GOTOOLCHAIN: "auto"

steps:
  - label: ":go: Run check-static"
    key: check
    command: "make check"
    agents:
      image: "${GO_LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"

  - group: "Run tests"
    key: "tests"
    steps:
      - label: ":linux: Tests on Linux"
        key: linux-test
        command: ".buildkite/scripts/run-linux-tests.sh"
        agents:
          image: "${GO_LINUX_AGENT_IMAGE}"
          cpu: "8"
          memory: "4G"
        artifact_paths:
          - build/test-results/*.xml

      - label: ":windows: Tests on Windows"
        key: windows-test
        command: ".buildkite/scripts/run-win-tests.ps1"
        env:
          # Latest 1.24 version in Chocolatey.
          GO_VERSION: 1.24.6
        agents:
          provider: "gcp"
          image: "${GO_WINDOWS_AGENT_IMAGE}"
        artifact_paths:
          - "*.xml"

      - label: ":pipeline: Trigger Compliance tests"
        command: ".buildkite/pipeline.trigger.compliance.tests.sh | buildkite-agent pipeline upload"

      # This step also ensures that result files from unit tests are all of them in the same directory
      - label: ":junit: Transform windows paths to linux for Junit plugin"
        key: preprocess-win-unit-results-files
        commands:
          - mkdir -p build/test-results
          - buildkite-agent artifact download *.xml build/test-results/ --step windows-test 
        artifact_paths:
          - "build/test-results/*.xml"
        depends_on:
          - step: "linux-test"
            allow_failure: true
          - step: "windows-test"
            allow_failure: true

      - label: ":junit: Junit annotate"
        agents:
          # requires at least "bash", "curl" and "git"
          image: "docker.elastic.co/ci-agent-images/buildkite-junit-annotate:1.0"
        plugins:
          - junit-annotate#v2.7.0:
              artifacts: "build/test-results/*.xml"
              report-skipped: true
              always-annotate: true
              fail-build-on-error: true
              run-in-docker: false
        depends_on:
          - step: "preprocess-win-unit-results-files"
            allow_failure: true

