env:
  SETUP_GVM_VERSION: 'v0.5.1' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  GO_LINUX_AGENT_IMAGE: "golang:${GO_VERSION}"
  GH_CLI_VERSION: "2.29.0"
  JQ_VERSION: "1.7"

  # Allow the use of go.mod toolchains, given that we have multiple go.mods in the repository.
  GOTOOLCHAIN: "auto"

steps:
  - label: ":go: Run check-static"
    key: check
    command: "make check"
    agents:
      image: "${GO_LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"
  - label: ":linux: Tests on Linux"
    key: test
    command: "make test-ci"
    agents:
      image: "${GO_LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"

  - label: ":hammer: Create PR in integrations"
    key: pr-integrations
    command: ".buildkite/scripts/test-with-integrations.sh"
    env:
      GITHUB_EMAIL: "elasticmachine@elastic.co"
      GITHUB_USERNAME: "elastic-vault-github-plugin-prod"
    plugins:
      # Required to push branches, create PRs and post comments on PRs
      - elastic/vault-github-token#v0.1.0:
    agents:
      provider: "gcp"
    depends_on:
      - check
      - test


