# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: 'v0.5.0' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  SETUP_MAGE_VERSION: "latest"
  GH_CLI_VERSION: "2.29.0"
  JQ_VERSION: "1.6"
  GO_LINUX_AGENT_IMAGE: "golang:${GO_VERSION}"
  GO_WINDOWS_AGENT_IMAGE: "family/ci-windows-2022"

steps:
  - label: ":go: Run check-static"
    key: check
    command: "make check"
    agents:
      image: "${GO_LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"

  - group: "Run tests"
    key: "tests"
    steps:
      - label: ":linux: Tests on Linux"
        key: linux-test
        command: ".buildkite/scripts/run-linux-tests.sh"
        agents:
          image: "${GO_LINUX_AGENT_IMAGE}"
          cpu: "8"
          memory: "4G"
        artifact_paths:
          - build/test-results/*.xml

      - label: ":windows: Tests on Windows"
        key: windows-test
        command: ".buildkite/scripts/run-win-tests.ps1"
        agents:
          provider: "gcp"
          image: "${GO_WINDOWS_AGENT_IMAGE}"
        artifact_paths:
          - build/test-results/*.xml

      - label: ":junit: Junit annotate"
        plugins:
          - junit-annotate#v2.4.1:
              artifacts: "build/test-results/*.xml"
        agents:
          provider: "gcp"
        depends_on:
          - step: "linux-test"
            allow_failure: true
          - step: "windows-test"
            allow_failure: true