# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: 'v0.5.0' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  SETUP_MAGE_VERSION: "latest"
  DOCKER_COMPOSE_VERSION: "v2.17.2"
  GO_VERSION: "1.20.3"
  GO_LINUX_AGENT_IMAGE: "golang:${GO_VERSION}"
  GO_WINDOWS_AGENT_IMAGE: "family/ci-windows-2022"

steps:
  - label: ":go: Run check-static"
    key: check
    command: "make check"
    agents:
      image: "${GO_LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"

  - group: "Run tests"
    key: "tests"
    steps:
      - label: ":linux: Tests on Linux"
        key: linux-test
        command: ".buildkite/scripts/run-linux-tests.sh"
        agents:
          image: "${GO_LINUX_AGENT_IMAGE}"
          cpu: "8"
          memory: "4G"
        artifact_paths:
          - build/test-results/*.xml

      - label: ":windows: Tests on Windows"
        key: windows-test
        command: ".buildkite/scripts/run-win-tests.ps1"
        agents:
          provider: "gcp"
          image: "${GO_WINDOWS_AGENT_IMAGE}"
        artifact_paths:
          - "*.xml"

      - label: "Elastic Stack {{matrix.stack_version}} compliance with Spec {{matrix.spec_version}}"
        command: ".buildkite/scripts/run-installer-compliance.sh {{matrix.stack_version}} {{matrix.spec_version}}"
        agents:
          provider: "gcp"
        matrix:
          # Skipped case here is a hack because buildkite wants a non-empty setup, and we want only
          # a list of sets of variables, that is only possible with adjustments.
          setup: {stack_version: skip, spec_version: skip}
          adjustments:
            - {with: {stack_version: skip, spec_version: skip}, skip: true}
            - with:
                stack_version: 8.10.0-SNAPSHOT
                spec_version: 2.10.0
            - with:
                stack_version: 8.9.0
                spec_version: 2.7.0

      - label: ":junit: Junit annotate"
        plugins:
          - junit-annotate#v2.4.1:
              artifacts: "*.xml"
              fail-build-on-error: true
        agents:
          provider: "gcp"
        depends_on:
          - step: "linux-test"
            allow_failure: true
          - step: "windows-test"
            allow_failure: true

